### ISSUE TITLE
Why does ssgsea give different values depending on number of samples? 

### ISSUE THREAD

**Issue by ahdee** [rcastelo/GSVA#101]
Hi, I think its my lack of understanding, but since ssGSEA only depends on a single sample should'nt the vaues produce be the same irrespective of how many samples I have? 

For example using log2 ( TPM + 1) values.

GSVA_1.34.0
R version 3.6.2 (2019-12-12)

 ```
set.seed(1)
temp <- GSVA::gsva(as.matrix ( tpmlog[ , 1:3] ), gsv_pathways, min.sz=30, max.sz=500000
              , mx.diff=TRUE, verbose=FALSE
              , parallel.sz=12
              ,  kcdf="Gaussian"
              , method = "ssgsea")
set.seed(1)
temp3 <- GSVA::gsva(as.matrix ( tpmlog[ , 1:40] ), gsv_pathways, min.sz=30, max.sz=500000
                   , mx.diff=TRUE, verbose=FALSE
                   , parallel.sz=12
                   ,  kcdf="Gaussian"
                   , method = "ssgsea")




> temp[1:3, 1:3 ]
                                     sup1       sup2       BD1
BP_ACID_SECRETION              0.3381399 0.3735195 0.3531354
BP_ACIDIC_AMINO_ACID_TRANSPORT 0.4231727 0.4492797 0.4654682
BP_ACROSOME_REACTION           0.2293610 0.2651850 0.2363289

> temp3[1:3, 1:3 ]
                                     sup1       sup2       BD1
BP_ACID_SECRETION              0.2773479 0.3063668 0.2896475
BP_ACIDIC_AMINO_ACID_TRANSPORT 0.3470931 0.3685065 0.3817846
BP_ACROSOME_REACTION           0.1881256 0.2175091 0.1938408
```

**Comment by rcastelo** [comment]
Hi, this has been already discussed at the [Bioconductor support site](https://support.bioconductor.org/p/p133739/#p133742). I'm copy&pasting here part of that answer.

The original proposal of the ssGSEA method in the article by [Barbie et al. (2009)](https://doi.org/10.1038/nature08460) says the following: "Signature values were normalized using the entire set of 128 lung adenocarcinomas and 17 normal lung specimens.", which means that up to some scale, the values may change from dataset to dataset if you use the normalization step that was originally proposed for the ssGSEA method. The GSVA package implements that default regime, which you may switch off by setting the argument `ssgsea.norm=FALSE` and then ssGSEA will truly operate using the information of each individual sample exclusively.

You may find questions like this about the methods implemented in GSVA by Googling with `site:support.bioconductor.org`. If you do not find the question answered at the [Bioconductor support site](https://support.bioconductor.org), I recommend you posting it there, as it works as a knowledge base for other users with similar questions, while keeping this `issues` tab in GitHub for bug reporting and features request.
