### ISSUE TITLE
A possible ranking issue in KS computation

### ISSUE THREAD

**Issue by NikTuzov** [rcastelo/GSVA#11]
Hello:

There may be an issue with how ranking is used when computing the KS statistic in formula (3) (I attached the paper and R code downloaded from Bioconductor). The paper says “Conceptually, Eq. 3 produces a distribution  over the genes to assess if the genes in the gene set are more likely to be found at either tail of the rank  distribution”. The “rank distribution” in question is the distribution of r_i_j values over the gene index “i” for a given sample j. That is, to compute KS, one needs to rank the r_i_j values. 

According to the paper, the computation proceeds as follows:

1) Compute the densities, z_i_j
2) Rank the densities to obtain the ranks, z_(i)_j
3) Compute r_i_j = abs(p/2 - z_(i)_j)
4) Compute KS based on r_i_j

In the attached R code, KS is computed by:

line 503 : ks_test_m <- function(gset_idxs, gene.density, sort.idxs,...)

I ran gsva() to see how it works and got the following results:

a) “gene.density” is actually r_i_j, not z_i_j
b) ks_test_m() is called in line 490 where the 3rd argument is set to sort.sgn.idxs
c) sort.sgn.idxs is computed in line 401 as follows: sorting is applied to the density, so sort.sgn.idxs is actually z_(i)_j, 2).

The problem (please correct me if I'm wrong) is that because of transformation in 3) the ordering of r_i_j is not the same as that of z_i_j. It looks like they assumed that 2) can be reused in 4), but that's not the case.

Besides, there is another (unused?) function for KS in the code:

ks_test_Rcode <- function(gene.density, gset_idxs, tau=1, make.plot=FALSE) 

If you look at the body and compare to the formula (3), it's clear that gene.density is again r_i_j, and, most important, the sorting is done as:

sort.idxs <- order(gene.density,decreasing=T)

That is, sorting is done wrt r_i_j, which I believe is the correct way. On the other hand, it looks like  ks_test_m() doesn't sort the r_i_j values properly. Please let us know what you think.

Regards,
Nik Tuzov

[Hanzelmann et al 2019.pdf](https://github.com/rcastelo/GSVA/files/3291755/Hanzelmann.et.al.2019.pdf)

[gsva.R.zip](https://github.com/rcastelo/GSVA/files/3291758/gsva.R.zip)

**Comment by rcastelo** [comment]
Hi, sorry for the delay in getting back to you. I've gone through the code and it is implementing correctly the method described in the paper. If you think there is a bug or anything that is not correctly calculated please show a reproducible example with the miscalculation, which should be the correct calculation and, that would be great, make a pull request with the fix.

There problem you refer to, by which r_i_j is not the same as that of z_i_j, is not a problem, they are indeed not the same. The code 'ks_test_Rcode()' is indeed not used and we had it there to do some internal testing, I do not see why that could be a problem to anyone. So, please be more precise in what is the actual problem you have with the calculations, otherwise I'm afraid I won't be able to help you further.

If you are trying to re-implement the method for a commercial tool of your own, or of your employer, and you need help in that task, you'll have to find your own way through the documentation and the code.

**Comment by NikTuzov** [comment]
Dear Prof. Castelo:

Thank you for replying. I think the problem is that, to compute KS based on r_i_j, one needs the ranks of r_i_j which are never computed. Instead, the code uses the ranks of z_i_j values that are not the same as the ranks of r_i_j values.

**Comment by rcastelo** [comment]
This is not true. Internally, the code is doing the following (I've change some of the names of the variable to match the notation we're discussing and enable running it outside the package):
```
library(GSVA)
set.seed(123) ## just for enabling reproducibility
example(gsva)
gset.idx.list <- lapply(geneSets, function(x ,y) na.omit(match(x, y)), y)
z_i_j <- GSVA:::compute.gene.density(y, 1:ncol(y), FALSE, TRUE)
sort.sgn.idxs <- apply(z_i_j, 2, order, decreasing=TRUE)
compute_rank_score <- function(sort_idx_vec, p){
  tmp <- rep(0, p)
  tmp[sort_idx_vec] <- abs(seq(from=p, to=1) - p/2)
  return (tmp)
}
r_i_j <- apply(sort.sgn.idxs, 2, compute_rank_score, nrow(y))
r_i_j[1:10, 1:10]
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]    4    1    3    2    2    1    0    3    3     2
 [2,]    1    1    0    4    1    3    4    4    1     1
 [3,]    1    2    1    0    4    2    1    2    4     2
 [4,]    2    2    1    5    5    5    2    1    2     1
 [5,]    4    3    2    4    4    0    3    1    0     3
 [6,]    5    5    4    2    3    3    1    5    1     3
 [7,]    3    3    4    3    0    4    3    0    4     5
 [8,]    2    4    3    1    1    4    2    2    3     4
 [9,]    3    4    2    3    3    1    4    3    2     0
[10,]    0    0    5    1    2    2    5    4    5     4
```
There were multiple hands coding in the package and this introduced inconsistencies in the naming of variables and functions and in the coding itself, but you can believe me that we spent quite some time making sure that the code implements what we say in the paper.

**Comment by NikTuzov** [comment]
Thank you for looking into this.
