### ISSUE TITLE
Does GSVA accept count data or gene length normalised data?

### ISSUE THREAD

**Issue by pooniasarita** [rcastelo/GSVA#12]
Dear Sir,
I have a query regarding the input matrix in gsva() method.
Does GSVA accept count data or gene length normalised data?

**Comment by rcastelo** [comment]
Hi, GSVA accepts both integer count and continuous units of expression. The relevant argument in the gsva() function is called 'kcdf', which by default is set to "Gaussian" and it means that it expects continuous units of expression, for count data you should set 'kcdf="Poisson"'. Note that this issues tab is more intended for package development questions and feature requests. For questions on using GSVA you should use the Bioconductor support site at https://support.bioconductor.org which also works as a knowledge base of answered questions. For instance, yours was already discussed in this [thread](https://support.bioconductor.org/p/119920/).
