### ISSUE TITLE
Questions about the parameter "ssgsea.norm" of ssGSEA

### ISSUE THREAD

**Issue by HMU-WH** [rcastelo/GSVA#135]
Hi

I found in the source code that if I set the parameter "ssgsea.norm" to TRUE, its normalization method is based on the maximum and minimum values ​​of the **entire matrix** (as shown in the picture), for which I have the following doubt:
![image](https://github.com/rcastelo/GSVA/assets/150757643/e64d4cfc-8eb9-49cd-8747-be6e48f7e8dc)

Q1: Why not perform separate normalization on **each gene set**? Although  the original proposal of the method in the article by Barbie et al. (2009) says the following: "Signature values were normalized using the entire set of 128 lung adenocarcinomas and 17 normal lung specimens.", I still don't quite understand why this normalization approach is used.

Q2: Is this normalized result comparable between samples? Is secondary standardization necessary?

Q3: If I want to compare the scores of different gene sets between samples, should I set the parameter "ssgsea.norm" to FALSE and then normalize the results myself?

Thank you.

**Comment by rcastelo** [comment]
Hi, sorry for the delay in getting back to you. These are questions regarding the ssGSEA method, which we implemented in the GSVA package, but which we did not develop, and therefore, to get an authoritative answer you should ask the authors of the ssGSEA method at the GenePattern [forum](https://groups.google.com/g/genepattern-help/search?q=ssgsea).

I can suggest you to use the GSVA method, which address this concerns within a dataset in a step before doing the gene set score summarization. You may find the details in the [paper](https://doi.org/10.1186/1471-2105-14-7).

**Comment by HMU-WH** [comment]
Thank you for your reply.发自我的 iPad在 2024年2月14日，16:30，Robert Castelo ***@***.***> 写道：﻿
Hi, sorry for the delay in getting back to you. These are questions regarding the ssGSEA method, which we implemented in the GSVA package, but which we did not develop, and therefore, to get an authoritative answer you should ask the authors of the ssGSEA method at the GenePattern forum.
I can suggest you to use the GSVA method, which address this concerns within a dataset in a step before doing the gene set score summarization. You may find the details in the paper.
