### ISSUE TITLE
Abs value of the rank?

### ISSUE THREAD

**Issue by xpeng-26** [rcastelo/GSVA#136]
I am confused about the reason to take the absolute value of the rank. All rank numbers are greater than 0, right?
https://github.com/rcastelo/GSVA/blob/d7778c0dd9519a4a016ea7069997809137dc99e3/R/gsva.R#L260C3-L260C21

I checked the original paper; it said, "The genes are replaced by their ranks according to _their absolute expression_ from high to low". I feel this sentence is saying to take the abs of the original expression value first, then replace it with the ranks.  Does my understand correctly?

Thanks for your time!

**Comment by rcastelo** [comment]
Hi, sorry for the delay in getting back to you. The GSVA package implements the ssGSEA method as described in the Barbie et al. (2009) [paper](https://doi.org/10.1038/nature08460), and more concretely, following the equation that one finds a few lines after the one you are quoting from the Online Methods section. As you can see, that equation takes the absolute value of the ranks and this is what the package implements. Looking at what apparently should the the [source code](https://github.com/GSEA-MSigDB/ssGSEA-gpmodule/blob/a882e2a5706f9c87c0e637123255f61cb5510e46/src/ssGSEA.Library.R#L328) of ssGSEA by the original authors of the method, I do not see indeed that they take the absolute value. To clear this up, you may try asking the authors of ssGSEA at the GenePattern [forum](https://groups.google.com/g/genepattern-help/search?q=ssgsea).
