### ISSUE TITLE
how to run GSVA on single cell RNA-seq gene expression matrix?

### ISSUE THREAD

**Issue by honghh2018** [rcastelo/GSVA#16]
Hi @rcastelo,
     Your GSVA  was very great contribution. And there are two problems perplexed me . Firstly, how can i run the GSVA package with single cell RNA-seq data and how to build the gmt file with mouse.
      Secondly, Why run single cell matrix so slowly, and occured error like, cholmod error 'problem too large' r .
      Hope your comment.

**Comment by zehualilab** [comment]
RunscGSVA <- function(object = object, assay = "SCT", slot = "data", geneset = geneset, ...) {
  object <- as.matrix(GetAssayData(object = object, assay = assay, slot = slot))
  object <- GSVA::gsva(expr = object, gset.idx.list = geneset, ...)
  return(object)
}

**Comment by rcastelo** [comment]
hi @honghh2018 

Apologies for the delay in getting back to your question. Next time, please use the Bioconductor support site at https://support.bioconductor.org to post questions about using GSVA. The issues tab in this GitHub site are more intended for development questions and feature requests.

Regarding your question about using GSVA with single-cell data, unfortunately I have no experience with that but some google search seems to point out that some other packages, such as [scMappR](https://cran.r-project.org/web/packages/scMappR) or [singleCellTK](https://bioconductor.org/packages/singleCellTK), are using GSVA for single-cell data analysis.

Regarding the performance issue that you mention, the current devel version of GSVA provides an improved way to launch calculations in parallel by using the [BiocParallel](https://bioconductor.org/packages/BiocParallel) package. This devel version will become release next Wednesday, so if you install the next BioC release 3.11 in a week, you should be able to calculate GSVA scores in parallel for large matrices of expression data.

Regarding how build a GMT file for mouse, this is not a GSVA related question.

I'm going to close this issue. If you have further questions, please post them at the Bioconductor support site but, before you do that, please read carefully the [Bioconductor posting guide](https://www.bioconductor.org/help/support/posting-guide).
