### ISSUE TITLE
res <- igsva() seem not work when use data from workspace

### ISSUE THREAD

**Issue by DDL095** [rcastelo/GSVA#166]
In the web application, I attempted to use both my data and the sample toy dataset provided in the GSVA Bioconductor package vignette[1](https://bioconductor.org/packages/devel/bioc/vignettes/GSVA/inst/doc/GSVA.html#5_Quantification_of_pathway_activity_in_bulk_microarray_and_RNA-seq_data), but neither worked.
The error messages are as follows. While the new feature gsvaParam functions correctly in the command line with BIOC_3.19, it does not work within the web application. Could the issue stem from the Gene Set option?”
![image](https://github.com/rcastelo/GSVA/assets/52679914/5c446a3c-5d6a-44f5-9579-1df5c86c4345)
![image](https://github.com/rcastelo/GSVA/assets/52679914/44996f5d-63f2-4e89-bdd0-3dc066d23f46)

**Comment by axelklenk** [comment]
Hi, thanks for reporting this.  
Clearly your second example is expected to work and I can reproduce the issue with Bioc 3.19/GSVA 1.52.0.
I'll look into it...

**Comment by axelklenk** [comment]
Hi again, the bug has been fixed in GSVA 1.52.1 which is now on its way to the BioC repos. 

In case you don't want to wait for it, you can of course use the devel version from GitHub
but as you said, it works on the command line and the bug was only affecting the shiny app.
