### ISSUE TITLE
Calling gsva is defunct, use a method-specific parameter object (error)

### ISSUE THREAD

**Issue by LnOp16** [rcastelo/GSVA#172]
R version 4.4.0 (2024-04-24 ucrt) -- "Puppy Cup"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64

**Comment by axelklenk** [comment]
Thanks for using GSVA.

The previous API of GSVA has been changed to make use of parameter objects and, as the message says, is now defunct after a full release cycle of deprecation.  If previously you have used
```gsva_es <- gsva(as.matrix(gsym.expr), gs)```
all you need to do is change it to 
```gsva_es <- gsva(gsvaParam(as.matrix(gsym.expr), gs))```

For more information about the new API, please do as the message says and see `?gsva` or the vignette at
https://bioconductor.org/packages/release/bioc/vignettes/GSVA/inst/doc/GSVA.html

Please don't hesitate to let us know if that doesn't solve the issue.
