### ISSUE TITLE
Error while installing the new GSVA from Bioconductor

### ISSUE THREAD

**Issue by Sa753** [rcastelo/GSVA#18]
Dear ,

I got the following error when I tried to install GSVA from bioconductor, could you please help?

clang: error: unsupported option '-fopenmp'
make: *** [blasctl.o] Error 1
ERROR: compilation failed for package ‘RhpcBLASctl’

Thank you

**Comment by rcastelo** [comment]
Installation problems may not be exclusively related to the package. Please post your question at the Bioconductor support site at https://support.bioconductor.org and we'll try to help there, but before you do that, please read carefully the Bioconductor [posting guide](https://www.bioconductor.org/help/support/posting-guide).

In particular, you need to give details about the version of your operating system the version of R that your are using and the specific commands that you are typing to install 'GSVA'. I'm going to close this issue, please post the question at the Bioconductor support site.
