### ISSUE TITLE
Support for GSEA plots

### ISSUE THREAD

**Issue by cihanerkut** [rcastelo/GSVA#192]
Would it be possible to implement a function that can plot (for a given gene set) a GSEA plot similar to the one here:

[https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html#running-score-and-preranked-list-of-gsea-result](https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html#running-score-and-preranked-list-of-gsea-result)

**Comment by rcastelo** [comment]
Hi, sure, I guess you mean to show such a plot for a specific column from your input data matrix, right?

In the meantime, you can have a try at the interactive web app described in [the vignette](https://bioconductor.org/packages/release/bioc/vignettes/GSVA/inst/doc/GSVA.html#7_Interactive_web_app), and you could try to obtain the plot from there.

**Comment by cihanerkut** [comment]
I tried that actually but the web app couldn't run GSVA because it required more memory, I guess, I'm not sure. Normally I run GSVA using `BPPARAM = BiocParallel::MulticoreParam(workers = 100)` on an RStudio Pro server with 128 cores and tons of memory. Even then it takes a while with the data and gene set list I am using. It would be nice if I did not have to rely on the shiny app.

I suggest we don't discuss the web app issue here as it is another issue. I can open up one for it, if you like.

**Comment by rcastelo** [comment]
I see, we will provide an alternative solution, no need to discuss the web app problem here. What kind of data (single-cell, bulk RNA-seq, proteomics, etc) and dimensions (rows/genes/transcripts x columns/cells/samples) do you need to input to GSVA?

**Comment by cihanerkut** [comment]
Around 50,000 genes x 4,000 samples as the expression data, and 20,000 gene sets.

**Comment by rcastelo** [comment]
ok, thanks, is the data sparse (more than 80% of the values) like if they were single-cell data?

**Comment by cihanerkut** [comment]
Not sparse at all. We already prefilter the data to remove genes with constant or no expression, so there *is* a TPM value for each gene in each sample.

**Comment by rcastelo** [comment]
Dear @cihanerkut yesterday we released a new version 2.0 of GSVA, see https://bioconductor.org/install for installation instructions, that includes a new function `gsvaEnrichment()` that will allow you to make GSEA-like plots from GSVA results. Please take a look to the help page of `gsvaEnrichment()` and do not hesitate to write back if anything is unclear.

**Comment by cihanerkut** [comment]
Dear @rcastelo , thanks a lot for your great support. I look forward to trying it :)
