### ISSUE TITLE
matrixStats  error

### ISSUE THREAD

**Issue by andreyurch** [rcastelo/GSVA#196]
gsvaPar <- ssgseaParam(s, pathways.hallmark)
> gsva.es <- gsva(gsvaPar, verbose=T)
Estimating ssGSEA scores for 20 gene sets.
[1] "Calculating ranks..."
Error in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 't': [matrixStats (>= 1.2.0)] useNames = NA is defunct. Instead, specify either useNames = TRUE or useNames = FALSE. See also ?matrixStats::matrixStats.options

**Comment by rcastelo** [comment]
https://support.bioconductor.org/p/9157686/#9157697
