### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by abadgerw** [rcastelo/GSVA#203]
@rcastelo thank you for a great package! I saw you instituted options for handling missing data. Is this something that can be done with the shiny app as well? In addition, are the options just available for ssgsea or other enrichment methods (gsva, etc) as well?

**Comment by rcastelo** [comment]
Hi, thanks for warning us about this missing feature in the shiny app. We added that feature to the software and forgot to added it to the shiny app, we'll certainly do it in the coming weeks. With regard to having the handling of missing data also available with the other enrichment methods, it is in our plans, but we cannot promise by now when we will have them available. We will let you know here when they become available, hopefully also soon.
