### ISSUE TITLE
Calling gsva(expr=., gset.idx.list=., method=., ...) is defunct

### ISSUE THREAD

**Issue by lucyu2668** [rcastelo/GSVA#213]
example(gsva)
es <- gsva(y, geneSets)
Error: gsva(y, geneSets): 
  Calling gsva(expr=., gset.idx.list=., method=., ...) is defunct; use a method-specific parameter object (see '?gsva').

My R version is 4.4.1, and GSVA 1.52.3

How to solve the problem?

**Comment by axelklenk** [comment]
From https://github.com/rcastelo/GSVA/issues/172 

Thanks for using GSVA.

The previous API of GSVA has been changed to make use of parameter objects and, as the message says, is now defunct after a full release cycle of deprecation. If previously you have used
```es <- gsva(y, geneSets)```
all you need to do is change it to
```es <- gsva(gsvaParam(y, geneSets))```

For more information about the new API, please do as the message says and see `?gsva` or the vignette at
https://bioconductor.org/packages/release/bioc/vignettes/GSVA/inst/doc/GSVA.html

Please don't hesitate to let us know if that doesn't solve the issue.
