### ISSUE TITLE
All the score are same

### ISSUE THREAD

**Issue by initialqy** [rcastelo/GSVA#22]
Hi, I analyzed scRNA-seq data, by "FindMarkers" I got the different gene expression matrix between control and treat group. so this matrix contains gene name in row, 2 samples in column, and the expression data. By "getGmt", I could get specific MSigDB dataset. then the codes are :
# myC7 <- getGmt("h.all.v7.1.symbols.gmt")
# score <- gsva(mydata, myC7,
              method= c("gsva", "ssgsea", "zscore", "plage"),
              kcdf=c("Gaussian", "Poisson", "none"),
              abs.ranking=F,
              min.sz=1,
              max.sz=Inf,
              parallel.sz=1L,
              mx.diff=T,
              #tau=switch(method, gsva=1, ssgsea=0.25, NA),
              ssgsea.norm=TRUE,
              verbose=T)
But I got Warning message:
Estimating GSVA scores for 3 gene sets.
Estimating ECDFs with Gaussian kernels
  |============================================================================| 100%

Warning message:
In .gsva(expr, mapped.gset.idx.list, method, kcdf, rnaseq, abs.ranking,  :
  Some gene sets have size one. Consider setting 'min.sz > 1'.

And all the scores of each pathway are same.
HALLMARK_COMPLEMENT	    -0.729128(control group)	   0.4434137(treat group)
HALLMARK_XENOBIOTIC_METABOLISM	-0.729128(control group)		0.4434137(treat group)
HALLMARK_COAGULATION	-0.729128(control group)		0.443413(treat group)

How could I do? Thank you.

**Comment by rcastelo** [comment]
hi,

the warning message and the fact that you're getting the same scores for each pathway are unrelated.

regarding the warning message, you should carefully read what it's saying: "Some gene sets have size one. Consider setting 'min.sz > 1'". a gene set of size one means that it's formed by one single gene and therefore, it does not make sense to summarize the expression for that gene set. to get rid of this warning message you should filter out those gene sets as follows:

```
mask <- lengths(geneIds(myC7)) > 1
myC7filt <- myC7[mask]
```
and use this object `myC7filt` when you call `gsva()`.

regarding the fact that you're getting the same score for each pathway, this is related to you input expression matrix, but you're not providing enough information to know what may be the problem. one issue is that, if i understood you correctly, your input expression matrix has two columns. with just two columns, it does not make sense to use the default method 'gsva' and i'd recommend you to use one of the other available methods by setting, for instance, `method="ssgsea"`.

as it says the README page of this GitHub repo, for questions and bug reports regarding the release version of GSVA please use the [Bioconductor support site](https://support.bioconductor.org). so i'm going to close this issue and if you want to continue this conversation please use that site. to increase the odds of solving your issue please provide more context, in particular:

* Describe a little bit your scRNA-seq data, how many genes, how many cells and what is this function `findMarkers()` that you're using, to what software package does it belong to.
* Give the output of the call to `dim(x)` where `x` is the object containing the gene expression matrix that you want to give as input to `gsva()`. show us the first rows and columns of that object with, e.g., `x[1:10, 1:10]`.
* Please read carefully the [Bioconductor posting guide](http://bioconductor.org/help/support/posting-guide) before doing your post. Remember to add a `gsva` tag to your question.

cheers,

robert.
