### ISSUE TITLE
Meaning of zero

### ISSUE THREAD

**Issue by ShixiangWang** [rcastelo/GSVA#3]
Hello,

After I plot density of `ssGSEA` method result, I am curious what the zero line means. As the documentation says, 

> GSVA assesses the relative enrichment of gene sets across samples using a non-parametric approach. 

If the mean of distribution locate at left of zero, does it mean this gene list of interest relatively un-enrich comparing with other genes in the genome??? 

![image](https://user-images.githubusercontent.com/25057508/42812349-f6be8688-89ef-11e8-834d-c425306537e2.png)

Best,
Shixiang

**Comment by rcastelo** [comment]
Hi,

as said at the bottom of the [README](https://github.com/rcastelo/GSVA) of this repo, this intended use of this issues page is to report bugs, feature requests or comments on the development version of GSVA. Please use the Bioconductor support site at [https://support.bioconductor.org](https://support.bioconductor.org) to post questions or bugs about the release version of GSVA, and please do read the [Bioconductor posting guide](http://bioconductor.org/help/support/posting-guide) before you write your post.

**Comment by ShixiangWang** [comment]
3q.
