### ISSUE TITLE
handle genes with the same expression

### ISSUE THREAD

**Issue by wt12318** [rcastelo/GSVA#32]
Hi,

I have read the code of gsva, and have a question: how to handle the genes with same expression (or the same order/rank)?
The code (line 706-805) seems to give different ranks to the genes that have same expression:

```
compute_rank_score <- function(sort_idx_vec){
		tmp <- rep(0, num_genes)
		tmp[sort_idx_vec] <- abs(seq(from=num_genes,to=1) - num_genes/2)
		return (tmp)
}
rank.scores <- rep(0, num_genes)
sort.sgn.idxs <- apply(gene.density, 2, order, decreasing=TRUE) # n.genes * n.samples
rank.scores <- apply(sort.sgn.idxs, 2, compute_rank_score)
```

Thank you.

**Comment by rcastelo** [comment]
This is explained in the GSVA [paper](http://www.biomedcentral.com/1471-2105/14/7), between Equations (2) and (3), the paragraph that starts with "Let $z_{ij} denote ...".
