### ISSUE TITLE
Implementation of the K-S statistic

### ISSUE THREAD

**Issue by lm687** [rcastelo/GSVA#4]
I am trying to wrap my head around the implementation of the random walk statistic (the positioning of tau, in particular) and how it's compatible with its definition in the paper:
[
<img width="388" alt="tau" src="https://user-images.githubusercontent.com/16312766/43681082-64b5de7a-9841-11e8-9096-d26bab30358f.png">
](url)

Shouldn't

``
stepCDFinGeneSet <- cumsum((abs(R[geneRanking, j]) * 
                      indicatorFunInsideGeneSet)^alpha) /
                      sum((abs(R[geneRanking, j]) *
indicatorFunInsideGeneSet)^alpha)
``

be in fact

`` 
stepCDFinGeneSet <- cumsum((abs(R[geneRanking, j])^alpha * 
                                indicatorFunInsideGeneSet)) /
    sum((abs(R[geneRanking, j])^alpha *
           indicatorFunInsideGeneSet))
``

? (the results don't differ unless tau=0). Thank you for your help.

**Comment by rcastelo** [comment]
Hi,

Sorry for the very long delay in answering this issue. This R code is a reflection of the underlying C code used by the 'gsva' method which is coded in this way for speed assuming that tau > 0, which is the default value. However, you're right that if you user would like to set tau=0 then, the code does not carry the correct calculation. I can fix that but do you in which situation the user may want to set tau=0?

**Comment by rcastelo** [comment]
Hi again, I have pushed the bugfix to current devel version 1.33.1. This bug only affects method="ssgsea" and the non-default argument value 'tau=0'. I'm closing the issue, if this does not resolve it, let me know and I'll open it again.
