### ISSUE TITLE
Gene identifier with GSVA

### ISSUE THREAD

**Issue by Clovernana** [rcastelo/GSVA#41]
Hi,
I have a  question about gene identifier. I promise I use the same type for gene names, such as symbol or ENTREZ id. I have run the same data and same code several days before.But today it doesn't work. The error is shown below.  I would appreciate  so much if you could help me.
![image](https://user-images.githubusercontent.com/50875585/107150308-26183c00-6998-11eb-9b33-610ab28c4da5.png)
Clover

**Comment by siyuangong** [comment]
Dear Clover,

I also run the code that worked several days ago. But when I run it again today, my R program also showed this error. I reinstalled all the packages but it still not worked. Have you fixed this problem? 

Siyuan

**Comment by rcastelo** [comment]
Hi, thanks for reporting, a couple of days ago I submitted a bugfix into the release version, which may have broken something else. I'm looking right now into this and let you know once is fixed here and at the Bioconductor support site.

**Comment by rcastelo** [comment]
Fixed on release version 1.38.2 and devel version 1.39.7. See my [answer](https://support.bioconductor.org/p/p134681/#p134686) at the Bioconductor support site.

**Comment by Clovernana** [comment]
OK




| |
姜娜
|
|
16622080827@163.com
|
签名由网易邮箱大师定制
On 2/9/2021 21:31，Robert Castelo<notifications@github.com> wrote：

Fixed on release version 1.38.2 and devel version 1.39.7. See my answer at the Bioconductor support site.
