### ISSUE TITLE
hgnc_symbol

### ISSUE THREAD

**Issue by indajuan** [rcastelo/GSVA#5]
Hi,

I wonder if there is a way to use hgnc_symbol instead of entrezgene.

Thanks

**Comment by rcastelo** [comment]
Hi,

sorry for the long delay to answer. You can use HGNC symbols. If the input gene sets are in a list object and/or the expression data in a matrix, then you need to take care by yourself to have those symbols in both data structures. If, however, you use a 'GeneSetCollection' object for the gene sets and a 'ExpressionSet' for the expression data, then the underlying 'GSEABase' infrastructure will take care of translating the gene identifiers.
