### ISSUE TITLE
parallel.sz Error

### ISSUE THREAD

**Issue by weipingz** [rcastelo/GSVA#53]
When I use the function gsva(), the following error was encountered.
iteration: Error in serialize(data, node$con, xdr = FALSE) : 
  error writing to connection
In addition: Warning messages:
1: In .filterFeatures(expr, method) :
  3501 genes with constant expression values throuhgout the samples.
2: In .filterFeatures(expr, method) :
  Since argument method!="ssgsea", genes with constant expression values are discarded.
3: In .gsva(expr, mapped.gset.idx.list, method, kcdf, rnaseq, abs.ranking,  :
  Some gene sets have size one. Consider setting 'min.sz > 1'.

Error in serialize(data, node$con, xdr = FALSE) : 
  error writing to connection

I don't know what is wrong, because this function ran successfully in the past. I restart the R, but it does not work.
Looking forward to your reply！ Thank you very much!

**Comment by PWbio** [comment]
I had the same issue (Only the error not the warning) both in linux and macOS. These issues happen when using `method="gsva"` but not `method="ssgsea"`. Also, I noticed that even if the errors have been prompted, the cores are still running and consuming the CPU resource in the background.

May I ask how you solved this error?

GSVA version tested on `1.38.2` and `1.41.1`

Here is the running code:
-----
`system.time({res.counts = gsva(expr, genesets, method="gsva", parallel.sz=2)}) 
`

Here is the error from macOS system
-----

Error in serialize(data, node$con, xdr = FALSE) : 
  error writing to connection 
18.
serialize(data, node$con, xdr = FALSE) 
17.
sendData.SOCK0node(backend[[node]], value) 
16.
parallel:::sendData(backend[[node]], value) 
15.
.send_to(cluster, i, .DONE()) 
14.
.send_to(cluster, i, .DONE()) 
13.
.bpstop_nodes(x) 
12.
.bpstop_impl(x) 
11.
bpstop(BPPARAM) 
10.
bpstop(BPPARAM) 
9.
.local(ITER, FUN, ..., BPPARAM = BPPARAM) 
8.
bpiterate(iter(expr, 100), compute.gene.density, sample.idxs = sample.idxs, 
    rnaseq = rnaseq, kernel = kernel, REDUCE = rbind, reduce.in.order = TRUE, 
    BPPARAM = BPPARAM) 
7.
bpiterate(iter(expr, 100), compute.gene.density, sample.idxs = sample.idxs, 
    rnaseq = rnaseq, kernel = kernel, REDUCE = rbind, reduce.in.order = TRUE, 
    BPPARAM = BPPARAM) 
6.
compute.geneset.es(expr, gset.idx.list, 1:n.samples, rnaseq = rnaseq, 
    abs.ranking = abs.ranking, parallel.sz = parallel.sz, mx.diff = mx.diff, 
    tau = tau, kernel = kernel, verbose = verbose, BPPARAM = BPPARAM) 
5.
.gsva(expr, mapped.gset.idx.list, method, kcdf, rnaseq, abs.ranking, 
    parallel.sz, mx.diff, tau, kernel, ssgsea.norm, verbose, 
    BPPARAM) 
4.
.local(expr, gset.idx.list, ...) 
3.
gsva(expr, genesets, method = "gsva", parallel.sz = 2) 
2.
gsva(expr, genesets, method = "gsva", parallel.sz = 2) 
1.
system.time({
    res.counts = gsva(expr, genesets, method = "gsva", parallel.sz = 2)
})

**Comment by pablo-rodr-bio2** [comment]
What are the sizes of `expr` and `genesets` in your case?

**Comment by PWbio** [comment]
> What are the sizes of `expr` and `genesets` in your case?

My original dataset is about [14000 genes x 5000 cells] for expression data and about 2000 Gene-sets.

I tried using simulated data found in [other website](https://support.bioconductor.org/p/9137111/) which encounter similar problems, and I found it works in different version of BiocParallel.

I tested it on the same version of `GSVA 1.41.1` with two different settings:

1. `BiocParallel 1.26.1` / `R 4.1.0` / `MacOS` (This one failed)
2. `BiocParallel 1.24.1` / `R 4.0.5` / `Linux` (This one worked)

So, I am thinking that it has something to do with the newer version of `BiocParallel`. Maybe I will tested it on the same OS system and R version later.

> And what is the result of running `parallel::detectCores()` in your machine?

The function reports that my MacOS has 4 cores and Linux has 96 cores.
But I set `parallel.sz=2` in both systems as following code.

```
p <- 1000 # Gene size
n <- 300 # Sample size                                                                                                                 
sizeGeneSets <- sample(10:500, size=100, replace=TRUE) # Gene-set size
geneSets <- lapply(as.list(sizeGeneSets), function(i) {sample(x=paste0("g", 1:p), size = i,replace=FALSE)})
names(geneSets) <- paste0("gs", 1:length(geneSets))

y <- matrix(rnorm(n*p), nrow=p, ncol=n,
            dimnames=list(paste("g", 1:p, sep="") , paste("s", 1:n, sep="")))
gsva_es <- gsva(y, geneSets, parallel.sz=2)
```

**Comment by weipingz** [comment]
> I had the same issue (Only the error not the warning) both in linux and macOS. These issues happen when using `method="gsva"` but not `method="ssgsea"`. Also, I noticed that even if the errors have been prompted, the cores are still running and consuming the CPU resource in the background.
> 
> May I ask how you solved this error?
> 
> GSVA version tested on `1.38.2` and `1.41.1`
> 
> ## Here is the running code:
> `system.time({res.counts = gsva(expr, genesets, method="gsva", parallel.sz=2)}) `
> 
> ## Here is the error from macOS system
> Error in serialize(data, node$con, xdr = FALSE) :
> error writing to connection
> 18.
> serialize(data, node$con, xdr = FALSE)
> 17.
> sendData.SOCK0node(backend[[node]], value)
> 16.
> parallel:::sendData(backend[[node]], value)
> 15.
> .send_to(cluster, i, .DONE())
> 14.
> .send_to(cluster, i, .DONE())
> 13.
> .bpstop_nodes(x)
> 12.
> .bpstop_impl(x)
> 11.
> bpstop(BPPARAM)
> 10.
> bpstop(BPPARAM)
> 9.
> .local(ITER, FUN, ..., BPPARAM = BPPARAM)
> 8.
> bpiterate(iter(expr, 100), compute.gene.density, sample.idxs = sample.idxs,
> rnaseq = rnaseq, kernel = kernel, REDUCE = rbind, reduce.in.order = TRUE,
> BPPARAM = BPPARAM)
> 7.
> bpiterate(iter(expr, 100), compute.gene.density, sample.idxs = sample.idxs,
> rnaseq = rnaseq, kernel = kernel, REDUCE = rbind, reduce.in.order = TRUE,
> BPPARAM = BPPARAM)
> 6.
> compute.geneset.es(expr, gset.idx.list, 1:n.samples, rnaseq = rnaseq,
> abs.ranking = abs.ranking, parallel.sz = parallel.sz, mx.diff = mx.diff,
> tau = tau, kernel = kernel, verbose = verbose, BPPARAM = BPPARAM)
> 5.
> .gsva(expr, mapped.gset.idx.list, method, kcdf, rnaseq, abs.ranking,
> parallel.sz, mx.diff, tau, kernel, ssgsea.norm, verbose,
> BPPARAM)
> 4.
> .local(expr, gset.idx.list, ...)
> 3.
> gsva(expr, genesets, method = "gsva", parallel.sz = 2)
> 2.
> gsva(expr, genesets, method = "gsva", parallel.sz = 2)
> 1.
> system.time({
> res.counts = gsva(expr, genesets, method = "gsva", parallel.sz = 2)
> })

**Comment by weipingz** [comment]
> I had the same issue (Only the error not the warning) both in linux and macOS. These issues happen when using `method="gsva"` but not `method="ssgsea"`. Also, I noticed that even if the errors have been prompted, the cores are still running and consuming the CPU resource in the background.
> 
> May I ask how you solved this error?
> 
> GSVA version tested on `1.38.2` and `1.41.1`
> 
> ## Here is the running code:
> `system.time({res.counts = gsva(expr, genesets, method="gsva", parallel.sz=2)}) `
> 
> ## Here is the error from macOS system
> Error in serialize(data, node$con, xdr = FALSE) :
> error writing to connection
> 18.
> serialize(data, node$con, xdr = FALSE)
> 17.
> sendData.SOCK0node(backend[[node]], value)
> 16.
> parallel:::sendData(backend[[node]], value)
> 15.
> .send_to(cluster, i, .DONE())
> 14.
> .send_to(cluster, i, .DONE())
> 13.
> .bpstop_nodes(x)
> 12.
> .bpstop_impl(x)
> 11.
> bpstop(BPPARAM)
> 10.
> bpstop(BPPARAM)
> 9.
> .local(ITER, FUN, ..., BPPARAM = BPPARAM)
> 8.
> bpiterate(iter(expr, 100), compute.gene.density, sample.idxs = sample.idxs,
> rnaseq = rnaseq, kernel = kernel, REDUCE = rbind, reduce.in.order = TRUE,
> BPPARAM = BPPARAM)
> 7.
> bpiterate(iter(expr, 100), compute.gene.density, sample.idxs = sample.idxs,
> rnaseq = rnaseq, kernel = kernel, REDUCE = rbind, reduce.in.order = TRUE,
> BPPARAM = BPPARAM)
> 6.
> compute.geneset.es(expr, gset.idx.list, 1:n.samples, rnaseq = rnaseq,
> abs.ranking = abs.ranking, parallel.sz = parallel.sz, mx.diff = mx.diff,
> tau = tau, kernel = kernel, verbose = verbose, BPPARAM = BPPARAM)
> 5.
> .gsva(expr, mapped.gset.idx.list, method, kcdf, rnaseq, abs.ranking,
> parallel.sz, mx.diff, tau, kernel, ssgsea.norm, verbose,
> BPPARAM)
> 4.
> .local(expr, gset.idx.list, ...)
> 3.
> gsva(expr, genesets, method = "gsva", parallel.sz = 2)
> 2.
> gsva(expr, genesets, method = "gsva", parallel.sz = 2)
> 1.
> system.time({
> res.counts = gsva(expr, genesets, method = "gsva", parallel.sz = 2)
> })

**In my case, it is because Seurat is conflict with GSVA. You need to restart a new R workspace and don't load SeuratObject, just loading required file.**

**Comment by PWbio** [comment]
> > I had the same issue (Only the error not the warning) both in linux and macOS. These issues happen when using `method="gsva"` but not `method="ssgsea"`. Also, I noticed that even if the errors have been prompted, the cores are still running and consuming the CPU resource in the background.
> > May I ask how you solved this error?
> > GSVA version tested on `1.38.2` and `1.41.1`
> > ## Here is the running code:
> > `system.time({res.counts = gsva(expr, genesets, method="gsva", parallel.sz=2)}) `
> > ## Here is the error from macOS system
> > Error in serialize(data, node$con, xdr = FALSE) :
> > error writing to connection
> > 18.
> > serialize(data, node$con, xdr = FALSE)
> > 17.
> > sendData.SOCK0node(backend[[node]], value)
> > 16.
> > parallel:::sendData(backend[[node]], value)
> > 15.
> > .send_to(cluster, i, .DONE())
> > 14.
> > .send_to(cluster, i, .DONE())
> > 13.
> > .bpstop_nodes(x)
> > 12.
> > .bpstop_impl(x)
> > 11.
> > bpstop(BPPARAM)
> > 10.
> > bpstop(BPPARAM)
> > 9.
> > .local(ITER, FUN, ..., BPPARAM = BPPARAM)
> > 8.
> > bpiterate(iter(expr, 100), compute.gene.density, sample.idxs = sample.idxs,
> > rnaseq = rnaseq, kernel = kernel, REDUCE = rbind, reduce.in.order = TRUE,
> > BPPARAM = BPPARAM)
> > 7.
> > bpiterate(iter(expr, 100), compute.gene.density, sample.idxs = sample.idxs,
> > rnaseq = rnaseq, kernel = kernel, REDUCE = rbind, reduce.in.order = TRUE,
> > BPPARAM = BPPARAM)
> > 6.
> > compute.geneset.es(expr, gset.idx.list, 1:n.samples, rnaseq = rnaseq,
> > abs.ranking = abs.ranking, parallel.sz = parallel.sz, mx.diff = mx.diff,
> > tau = tau, kernel = kernel, verbose = verbose, BPPARAM = BPPARAM)
> > 5.
> > .gsva(expr, mapped.gset.idx.list, method, kcdf, rnaseq, abs.ranking,
> > parallel.sz, mx.diff, tau, kernel, ssgsea.norm, verbose,
> > BPPARAM)
> > 4.
> > .local(expr, gset.idx.list, ...)
> > 3.
> > gsva(expr, genesets, method = "gsva", parallel.sz = 2)
> > 2.
> > gsva(expr, genesets, method = "gsva", parallel.sz = 2)
> > 1.
> > system.time({
> > res.counts = gsva(expr, genesets, method = "gsva", parallel.sz = 2)
> > })
> 
> **In my case, it is because Seurat is conflict with GSVA. You need to restart a new R workspace and don't load SeuratObject, just loading required file.**

When I tested with simulated data, I didn't load `Seurat`. Thanks for suggestion. It may help others 😅

**Comment by pablo-rodr-bio2** [comment]
I did the same test with `BiocParallel` 1.24.1 / 1.26.1 and R 4.1 on Linux and it worked.
So we can narrow the problem to `MacOS`.
Maybe we can add parallel tests to `GSVA` and run them in Github Actions using `MacOS` to see if we can reproduce the error.
Doing a little google research the error seems related to instances were the machine runs out of cores or RAM memory to fork the process being done in parallel. When you launch the `gsva()` function, are all cores in standby or are they already being used? How much RAM memory do you have left before using the `GSVA` function?
Strange, if the problem seems related to cores/memory availability, I still don't see why it fails using `method="gsva"` but not using `method="ssgsea"`
