### ISSUE TITLE
how to get the pathways with gene name enriched such as we do in clusterProfiler

### ISSUE THREAD

**Issue by jinaanna** [rcastelo/GSVA#56]
Hello!

Thanks for your work in GSVA r package. I have a question about this package. That is, how to get the pathways with gene name enriched such as we do in clusterProfiler?  The format can be like this:

![0C9FF68E-ACAF-4AD3-94C0-814A0C77E2D0](https://user-images.githubusercontent.com/91006223/139630423-7cedbb14-352e-4153-b9f6-13884add9fdb.png)

Looking forward to your reply!

Clover

**Comment by rcastelo** [comment]
Hi Clover, please look at the [vignette](http://bioconductor.org/packages/release/bioc/vignettes/GSVA/inst/doc/GSVA.html) of the package and if you tell me what part you don't understand I might be able to help.

cheers,
robert.

**Comment by jinaanna** [comment]
I have read the vignette of the package. I mean that when I finished the differential expression at pathway level, how to find the genes associated with some pathway? I think the package didn't tell us.


Thank you!


| |
jina
|
|
***@***.***
|
签名由网易邮箱大师定制
On 11/2/2021 17:29，Robert ***@***.***> wrote：

Hi Clover, please look at the vignette of the package and if you tell me what part you don't understand I might be able to help.

cheers,
robert.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rcastelo** [comment]
The GSVA package doesn't do any differential expression (DE) analysis, you must be doing your DE analysis with another package (limma?) and how you extract the results from your DE analysis depends on how you do that with that package. I recommend you reading the documentation of that package.

**Comment by jinaanna** [comment]
I think maybe I didn't specify the problems clearly. Yes, GSVA doesn't perform any differential analysis. The gene-to-sample data matrix become the geneset-to-sample matrix (Enrichment score) in the GSVA analysis process. I want to know how to find the relationship between observed genes in the experiment with the geneset? Maybe I can just make a interaction between the gene ID used for the GSVA analysis and geneids in some pathway I interested, such as "c2.cp.v7.4.symbols.gmt" in MsigDB?


Clover
| |
jina
|
|
***@***.***
|
签名由网易邮箱大师定制
On 11/2/2021 18:29，Robert ***@***.***> wrote：

The GSVA package doesn't do any differential expression (DE) analysis, you must be doing your DE analysis with another package (limma?) and how you extract the results from your DE analysis depends on how you do that with that package. I recommend you reading the documentation of that package.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jinaanna** [comment]
OK. Thank you !




| |
jina
|
|
***@***.***
|
签名由网易邮箱大师定制
On 11/3/2021 23:32，Robert ***@***.***> wrote：

If what you want is to know what genes form each gene set in a MSigDB collection such as the C2 stored in the file c2.cp.v7.4.symbols.gmt, then this has nothing to do with GSVA, you can do that easily in R with the Bioconductor package GSEABase as follows:

library(GSEABase)
download.file("https://data.broadinstitute.org/gsea-msigdb/msigdb/release/7.4/c2.cp.v7.4.symbols.gmt",
              "c2.cp.v7.4.symbols.gmt")
c2gs <- getGmt("c2.cp.v7.4.symbols.gmt")
c2gs
GeneSetCollection
  names: BIOCARTA_GRANULOCYTES_PATHWAY, BIOCARTA_LYM_PATHWAY, ..., REACTOME_ION_CHANNEL_TRANSPORT (2922 total)
  unique identifiers: CXCL8, IFNG, ..., TSPAN5 (13351 total)
  types in collection:
    geneIdType: NullIdentifier (1 total)
    collectionType: NullCollection (1 total)
geneIds(c2gs[["BIOCARTA_GRANULOCYTES_PATHWAY"]])
 [1] "CXCL8"  "IFNG"   "IL1A"   "CSF3"   "SELP"   "ITGAM"  "ITGAL"  "TNF"   
 [9] "ITGB2"  "PECAM1" "ICAM2"  "C5"     "SELPLG" "ICAM1"  "SELL"  


To learn more about how to manipulate these GeneSetCollection objects returned by the function getGmt(), please read the documentation of the GSEABase package and if you have further questions about this, please use the Bioconductor support site, since this topic is not directly related with the GSVA package.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
