### ISSUE TITLE
Question about data input for gsva()

### ISSUE THREAD

**Issue by bieniu777** [rcastelo/GSVA#57]
Hello,

I wanted to ask about the gsva() function. I am using it to calculate ssGSEA scores in TCGA samples. I have 25 genes sets for which I calculate these scores.
In this 25 gene sets I have around 700 unique genes. So my question is: when I calculate the scores - should I subset the expression data (input for expr argument) to include only the genes that I have in my gene sets? Or is it better to keep all the genes that were originally in the expression data?

I think with the subsetting I am able to see clearer differences between my gene sets (when I visualise them on a heatmap), however I am not sure if it is a correct approach and perhaps I should keep all genes in the input matrix instead.

Can I also ask about the mx.diff argument? I know the default is set to TRUE, however I don't really understand the difference between the two methods available. Which one would be more suitable to identify specific cell phenotypes in bulk based on input gene signatures? 

I would appreciate any help,

Best wishes

**Comment by rcastelo** [comment]
hi, the ssGSEA method calculates its enrichment scores taking into account what genes are inside a gene set and what genes are outside, from that perspective you don't want to have only genes inside a gene set in your input expression data. On the other hand, just as with differential expression analysis, you don't want to input expression profiles from genes that are lowly expressed in most of the samples and therefore, you may want to filter those out. This kind of question has been already discussed at the Bioconductor support site [here](https://support.bioconductor.org/p/107922) and [here](https://support.bioconductor.org/p/107922). If you are using `method="ssGSEA"`, then the parameter `mx.diff` is not used, it's only relevant if you use the default `method="gsva"`.

Issues in this repo are supposed to be more about bugs and feature requests. I'll appreciate if next time you have this type of question you use the Bioconductor [support site](https://support.bioconductor.org). Thanks!

**Comment by bieniu777** [comment]
Hi,

Thank you very much for your reply. Really helpful.
(I will use Bioconductor for this type of questions next time.)

Best wishes
