### ISSUE TITLE
The meaning of negative enrichemnt scores resulting from gsva

### ISSUE THREAD

**Issue by charlesgwellem** [rcastelo/GSVA#62]
Thank you for this great package. Please is there an explanation why there are negative enrichment scores and what they could mean? I understand that while comparing two groups, one group being negative will imply that the group with positive values  is enriched for a certain signature. But what if both groups have negative or positive values? E.g. see plot below:

![grafik](https://user-images.githubusercontent.com/10155881/179951984-8600dc99-6427-4724-853a-e3954082b43f.png)

Thanks for your helpful response.

**Comment by rcastelo** [comment]
The question about what do negative GSVA scores mean has been asked a number of times in the [Bioconductor support site](https://support.bioconductor.org) (see [here](https://support.bioconductor.org/p/9145297), [here](https://support.bioconductor.org/p/84439), [here](https://support.bioconductor.org/p/9142545), [here](https://support.bioconductor.org/p/119709) and [here](https://support.bioconductor.org/p/111171)), which is a better place to post this type of questions as it works as a knowledge base of answers that helps users finding whether their question has been already addressed. The issues tab here is more intended for bug reporting and feature requests.

You should read those posts to see whether those discussions fit your specific question, but in short, a negative score for a gene set in a sample implies that genes forming that gene set are down in the ranking of expression for that sample in comparison with the genes outside that gene set. You can use the GSVA shiny app, starting it with `igscores()` to visualize that ranking and get a better understanding of why you're getting those negative scores.
