### ISSUE TITLE
Vignette issue

### ISSUE THREAD

**Issue by UboCA** [rcastelo/GSVA#63]
Hi, thanks for your great tool!

The Rmd in vignette produces gene set list as follows:
```
gs <- lapply(gs, function(n, p)
                   paste0("g", sample(1:p, size=n, replace=FALSE)), p)
names(gs) <- paste0("gs", 1:length(gs))
```

Here, the global variable p is not necessary for `lapply()`

And the following command should be OK.

```
gs <- lapply(gs, function(n)
                   paste0("g", sample(1:p, size=n, replace=FALSE)))
names(gs) <- paste0("gs", 1:length(gs))
```

Best~

**Comment by rcastelo** [comment]
hi, I know and this is a trivial case, but avoiding the use of global variables is a good programming practice and I just like to follow it even in such tiny examples.
