### ISSUE TITLE
P-value calculation

### ISSUE THREAD

**Issue by andreyurch** [rcastelo/GSVA#7]
Dear GSVA team,

Thank you for a very useful tool.
I have a question regarding the p-values of the enrichment significance. I understand that is is not implemented in the GSVA algorithm, but how about permutation-based p-values for ssGSEA? Could you let me know how to find them in output if they are implemented into the tool?

Best regards,
Andrey

**Comment by rcastelo** [comment]
Hi, sorry for the long delay in getting back to your. There is no implementation of any permutation-based p-value calculation for ssGSEA in the GSVA package.
