### ISSUE TITLE
zscore method parameter class and constructor

### ISSUE THREAD

**Issue by rcastelo** [rcastelo/GSVA#73]
Create a parameter class and constructor function for the zscore method.

**Comment by axelklenk** [comment]
Added the class definition(s) and constructor in new file allClasses.R (following nomenclature from atena).
In addition, I had to 
 - change DESCRIPTION to set Encoding from Latin1 to UTF-8 as required by Roxygen2
 - change NAMESPACE as concatenation of old (manual?) and new, generated by Roxygen2
I suppose, eventually we want to port all documentation to Roxygen2?

However, most of time I have spent trying to fix a build issue in the vignette where an X11 font couldn't be loaded.
(Until I figured out that I actually need to reboot the machine after font installation.)

As of this commit, #73 is done but check() finds 2 remaining NOTEs and 2 WARNINGs.

**Comment by axelklenk** [comment]
And I have succeeded in eliminating the two WARNINGs by installing additional packages on my laptop.

One of the notes is about this:
>   Found if() conditions comparing class() to string:
>   File ‘GSVA/R/gsva.R’: if (parallel.sz > 1L && class(BPPARAM) == "SerialParam") ...
>   File ‘GSVA/R/gsva.R’: if (parallel.sz == 1L && class(BPPARAM) != "SerialParam") ...
>   File ‘GSVA/R/gsva.R’: if (parallel.sz > 1L && class(BPPARAM) != "SerialParam") ...
>   File ‘GSVA/R/gsva.R’: if (class(BPPARAM) != "SerialParam" && verbose) ...
>   File ‘GSVA/R/gsvaDelayedArray.R’: if (parallel.sz > 1L && class(BPPARAM) == "SerialParam") ...
>   File ‘GSVA/R/gsvaDelayedArray.R’: if (parallel.sz == 1L && class(BPPARAM) != "SerialParam") ...
>   File ‘GSVA/R/gsvaDelayedArray.R’: if (parallel.sz > 1L && class(BPPARAM) != "SerialParam") ...
>   File ‘GSVA/R/gsvaDelayedArray.R’: if (class(BPPARAM) != "SerialParam" && verbose) ...
>   Use inherits() (or maybe is()) instead.


and I could easily fix that one, too, in a different branch, if you agree.

**Comment by rcastelo** [comment]
This will be fixed in issue #76

**Comment by rcastelo** [comment]
Hi, the two PRs fixing the `--as-cran` warnings/notes have been merged, so now this issue, and the one on the PLAGE API, can resume on the updated code by pulling the updated contents of the 'devel' branch upstream, where I also fixed a minor note from `--as-cran` about an URL in the `inst/CITATION` file. I've seen that this issue appears in the "Done" column of the project, but this should not yet happen, as you still have to do a PR. How is this possible?

**Comment by axelklenk** [comment]
Thanks for merging the two PRs -- I was wondering who should do this and strongly agree that it should be you, so a second person gets to see and check my changes.

W.r.t. this issue, when I considered it finished I 
1. set the status to "Done" and 
2. pushed local to GH and then merged the issue's branch into the new branch 'new_api' directly, without a PR.   
I think I could still create one if you prefer that.

My understanding of our discussion on Thursday was that we'd try to fix the `--as-cran` notes in branch devel for the pending Bioc release, not including any modifications to the API. For the next release, we continue to accumulate smaller changes to the API, e.g. the PLAGE issue/branch etc., in branch 'new_api' which is potentially squashed and eventually merged into devel. If you'd prefer another approach, just let me know.

**Comment by rcastelo** [comment]
Ok, you're right, we talked about that it would go into this 'new_api' branch. I think we should find a way to keep track then of this 'new_api' branch, otherwise we could have bunch of 'issues' tagged as done, but no code is updated in the package. Should we open a new issue called something like 'New API' ?

**Comment by axelklenk** [comment]
... and then link the existing branch or, if necessary, create a new branch, to that new issue? -- sounds like a good idea to me.

For the upcoming Bioc push/submission, ist that something that you will take care of or can I contribute somehow?

**Comment by rcastelo** [comment]
well, you already created the branch 'new_api', right? this means we only would need a new issue. In any case, we won't merge this 'new_api' branch in the upcoming Bioc release, but during the next devel cycle. Could you try to create the 'new_api' branch in the GitHub repo and open a new issue associated with it?

**Comment by axelklenk** [comment]
Ok, I'll try to create such an issue and link the existing branch to it.
