### ISSUE TITLE
There is no package named 'GenomeInfoDbData'.

### ISSUE THREAD

**Issue by ccartermices** [rcastelo/GSVA#75]
Hey！ Here are the bug i met:
library('GSVA')
Error: package or namespace load failed for ‘GSVA’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
There is no package named 'GenomeInfoDbData'.

I have installed GSVA successfully through bioconductor and i pick this GenomeInfoDb and GenomeInfoDbData into my library manually, but it still cannot work. And, my R version is 4.2.3.

How to fix this? Thx!

**Comment by rcastelo** [comment]
hi,

the GSVA package does not import any functionality of the GenomeInfoDbData. Most likely, this error comes from another instruction you put before `library(GSVA)`. If you want to verify what I'm saying, do the following steps:

1. Start a fresh R session, i.e., the output of a call to `search()` and `ls()` should look like this:
```
> search()
 [1] ".GlobalEnv"        "package:stats"     "package:graphics" 
 [4] "package:grDevices" "package:utils"     "package:datasets" 
 [7] "package:colorout"  "package:methods"   "Autoloads"        
[10] "package:base"     
> ls()
character(0)
```
2. Install again the GSVA package, with the argument `force=TRUE` to overwrite any previous installation of GSVA:
```
> BiocManager::install("GSVA", force=TRUE)
```
3. Load the GSVA package, and you should get no error after loading it:
```
library(GSVA)
```

In any case, whatever caused you error, the error is saying that you need a package called `GenomeInfoDbData`. To fix that, you just need to install that package by typing:
```
> BiocManager::install("GenomeInfoDbData")
```

**Comment by ccartermices** [comment]
Thx！I reintalled R and it worked.
