### ISSUE TITLE
number of input gene sets

### ISSUE THREAD

**Issue by alpreyes** [rcastelo/GSVA#8]
hello, I am trying to use GSVA to calculate an enrichment score of the HRD pathway. I am inputting into the gsva function a gene expression count matrix and a list object of genes in the hrd pathway. I am getting results but am having trouble interpreting them. Is there a minimum number or specific combination of gene sets that need to be input into the gsva function?

**Comment by rcastelo** [comment]
Hi, sorry for the long delay in getting back to you. You can calculate GSVA enrichment scores with just one gene set if you wish. Try this:

```
library(GSVA)
example(GSVA)
gsva(y, geneSets[1])

```
the gene set, however, needs to be passed to the gsva() function within a list or a GeneSetCollection object.

**Comment by rcastelo** [comment]
I'm closing this issue, if you have further questions about using GSVA please use the Bioconductor support site at https://support.bioconductor.org as this issues tab is more intended for package development questions and feature requests.
