### ISSUE TITLE
NES in ssGSEA

### ISSUE THREAD

**Issue by chunxuan-hs** [rcastelo/GSVA#89]
I would like to run ssgsea implemented in GSVA. The `ssgsea.norm=TRUE` "normalizing the scores by the absolute difference
between the minimum and the maximum, as described in their paper.", but how could I get the NES score as in the package [link](https://github.com/nicolerg/ssGSEA2)? Many thanks!

**Comment by rcastelo** [comment]
Hi, the implementation of ssGSEA in GSVA correspond to the first version, the one published in Barbie et al. (2009). So, the parameter `ssgsea.norm=TRUE` refers to the normalization procedure described in the Barbie et al. (2009) publication and has nothing to do with the "normalized enrichment score (NES)" you mentioned, and which is defined in the publication cited in the link you are pointing out to.
