### ISSUE TITLE
Listing genes from a pathway

### ISSUE THREAD

**Issue by toddcreasy** [rcastelo/GSVA#9]
Is there a way in GSVA to obtain the genes that make up the pathways that are identified as differentially expressed? I can go to msigdb and enter the pathway, of course, but it would be nice to pull this up in R code.

Thanks

**Comment by rcastelo** [comment]
Hi, sorry for the delay in getting back to you. This is not a GSVA-specific question. If you are using GSVA, you must have some object, either a list or a GeneSetCollection object, that contains the gene set definitions, i.e., what genes form each gene set. Just use that object to fetch the genes belonging to whatever gene sets you're interested in, such as those that you may call differentially expressed.

**Comment by rcastelo** [comment]
I'm closing this issue, if you have further questions about using GSVA please use the Bioconductor support site at https://support.bioconductor.org as this issues tab is more intended for package development questions and feature requests.
